import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Header from "./components/header/header";
import Dots from "./components/dots/dots";



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Dots />
        <Header />
        {children}
      </body>
    </html>
  );
}
